### ISSUE TITLE
Problem on mobile

### ISSUE THREAD

**Issue by Jobisss** [joaogabriel-customcode/nex-clone#16]
## do desktop para o mobile
![image](https://github.com/user-attachments/assets/38cd7cb3-be84-4df6-8db7-2eb67386c1af)

## direto do mobile 
![image](https://github.com/user-attachments/assets/b6b09fbb-e28d-4d4b-904c-8d3e9d68a25d)

**Comment by joaogabriel-customcode** [comment]
#21 resolved this issue.
